### ISSUE TITLE
Update to 2.7.7 causes compile errors

### ISSUE THREAD

**Issue by codeboten** [sijms/go-ora#389]
Bumping the dependency from 2.7.6 to 2.7.7 causes the following error message in our build which uses go 1.19:

```
Error: /home/runner/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.7/utils.go:559:8: value.SetZero undefined (type reflect.Value has no field or method SetZero)
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5336076619/jobs/9670223260#step:5:40824

**Comment by ccampo133** [comment]
Yep, the issue is here: https://github.com/sijms/go-ora/blob/v2.7.7/v2/utils.go#L559

Note that `SetZero` method of `reflect.Value` was not added until Go 1.20 (see: https://pkg.go.dev/reflect#Value.SetZero)

Either `go-ora` needs to set the minimum Go version to 1.20 in https://github.com/sijms/go-ora/blob/master/v2/go.mod, or find another way to implement the functionality added by `SetZero`.

**Comment by sijms** [comment]
I replace `value.SetZero()` with `value.Set(reflect.Zero(value.Type()))` in new release
